Billing stripe list payment methods
sap-labs-france/ev-server pull request #2208
Opened 2021-03-19 14:25 UTC by cabch

list, create and delete payment method

2021-03-20 07:22 UTC, ClaudeROSSI commented on src/authorization/AuthorizationsDefinition.ts
> +      // },
@LucasBrazi06 : Temporary solution to make sure BASIC Users do not see the billing stuff

2021-03-20 07:27 UTC, LucasBrazi06 commented on src/authorization/AuthorizationsDefinition.ts
> +      // },
> @LucasBrazi06 : Temporary solution to make sure BASIC Users do not see the billing stuff

Okay

2021-03-20 07:46 UTC, ClaudeROSSI requested changes

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +  public async paymentMethodsList(user: User): Promise<DataResult<BillingPaymentMethod>> {
the term 'List' is useless ... and not in the 'spirit' of existing stuff.

I would suggest to get rid of LIST every where.

the name should be getPaymentMethods!

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/BillingIntegration.ts
> +  abstract paymentMethodsList(user: User): Promise<BillingPaymentMethodResult>;
??? getPaymentMethods() ... please rename it!

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +    if (!user?.billingData?.customerID || await this._isDeletedInStripe(user?.billingData?.customerID)) {
_isDeletedInStripe() ... I'm not sure.
If we keep it here, we then need to do the same everywhere!

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +            expiringOn: (paymentMethod.card.exp_month).toString().padStart(2, '0') + '/' + paymentMethod.card.exp_year,
'/' as separator ??? are we sure that this is ok for over locales? 
Maybe we need here a a i18n text or a formatting using the locale.

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +            createdOn: new Date((paymentMethod.created) * 1000),
I don't like the *1000

please use moment instead:
moment.unix(paymentMethod.created).toDate();

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +    const paymentMethodsList = [] as BillingPaymentMethod[];
same comment ... rename it to paymentMethods!

Can we type the array here???
Please avoid using 'as' keyword when possible

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +  private async _getPaymentMethodsList(user: User, customerID: string): Promise<DataResult<BillingPaymentMethod>> {
_getPaymentMethods()

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +        message: `Stripe operation failed - ${e?.message as string}`
@LucasBrazi06 : I'm not sure how to proceed here ... do we need to keep the stack of the stripe error as details?
What would you recommend?

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +  private async _isDeletedInStripe(customerID: string): Promise<boolean> {
shoud be part of the regular getStripeCustmer() method.
I'll take care of refactoring this!

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/server/rest/CentralRestServerService.ts
> +          [ServerAction.BILLING_PAYMENT_METHODS_LIST]: BillingService.handleBillingGetPaymentMethodsList.bind(this),
same comment: remove _LIST suffix

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/server/rest/v1/router/api/BillingRouter.ts
> +  protected buildRoutePaymentMethodsList(): void {
idem

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/server/rest/v1/router/api/BillingRouter.ts
> +    this.buildRoutePaymentMethodsList();
here the name is even more confusing. 
Please stick to the naming convention used for other entities

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    res.json(Constants.REST_RESPONSE_SUCCESS);
@LucasBrazi06 : I'm lost regarding the regular express flow.
do we need to call next() as well????

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/types/Authorization.ts
> +  BILLING_PAYMENT_METHODS_LIST = 'BillingPaymentMethodsList',
idem

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/types/Billing.ts
> +  expiringOn: string;
I woud suggest to have two properties : one for the month and a second one for year.
This will then allow us to solve the separator issues client-side and support stuff like right-to-left languages

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/types/Server.ts
> +  BILLING_PAYMENT_METHODS_LIST = 'BillingPaymentMethodsList',
idem

2021-03-20 07:46 UTC, ClaudeROSSI commented on src/types/requests/HttpBillingRequest.ts
> +export interface HttpPaymentMethodsList {
idem

2021-03-22 11:11 UTC, cabch commented on src/integration/billing/BillingIntegration.ts
> +  abstract paymentMethodsList(user: User): Promise<BillingPaymentMethodResult>;
renamed

2021-03-22 11:11 UTC, cabch commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +  public async paymentMethodsList(user: User): Promise<DataResult<BillingPaymentMethod>> {
renamed

2021-03-22 11:11 UTC, cabch commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +  private async _getPaymentMethodsList(user: User, customerID: string): Promise<DataResult<BillingPaymentMethod>> {
renamed

2021-03-22 14:04 UTC, cabch commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +            expiringOn: (paymentMethod.card.exp_month).toString().padStart(2, '0') + '/' + paymentMethod.card.exp_year,
changed with sending a date like 31/month/year (as cards expires "end of" month/year)
front side I used the date pipe but no existing MM/YYYY exists for all locations so I used the "short date" instead ... To be decided front end

2021-03-22 14:32 UTC, cabch commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +            createdOn: new Date((paymentMethod.created) * 1000),
done

2021-03-22 14:33 UTC, cabch commented on src/server/rest/CentralRestServerService.ts
> +          [ServerAction.BILLING_PAYMENT_METHODS_LIST]: BillingService.handleBillingGetPaymentMethodsList.bind(this),
done

2021-03-22 14:35 UTC, cabch commented on src/server/rest/v1/router/api/BillingRouter.ts
> +    this.buildRoutePaymentMethodsList();
called it buildRoutePaymentMethods

2021-03-22 14:35 UTC, cabch commented on src/server/rest/v1/router/api/BillingRouter.ts
> +  protected buildRoutePaymentMethodsList(): void {
done

2021-03-22 14:36 UTC, cabch commented on src/types/Authorization.ts
> +  BILLING_PAYMENT_METHODS_LIST = 'BillingPaymentMethodsList',
doone

2021-03-22 14:38 UTC, cabch commented on src/types/Billing.ts
> +  expiringOn: string;
kept the expiringOn as a Date so we handle it as we need front side, need to show you before ruling

2021-03-22 14:38 UTC, cabch commented on src/types/Server.ts
> +  BILLING_PAYMENT_METHODS_LIST = 'BillingPaymentMethodsList',
done

2021-03-22 15:32 UTC, cabch commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +    const paymentMethodsList = [] as BillingPaymentMethod[];
done

2021-03-22 17:09 UTC, ClaudeROSSI approved these changes

2021-03-23 06:38 UTC, ClaudeROSSI approved these changes

2021-03-23 07:42 UTC, merged