Payment method (pm) polish
sap-labs-france/ev-server pull request #2222
Opened 2021-03-24 10:12 UTC by cabch

added tests assign/detach/verify
added missing next()s
repaired getTaxes()

2021-03-24 13:46 UTC, ClaudeROSSI requested changes
asked for a few minor changes.

2021-03-24 13:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
>      const taxes = [] as BillingTax[];
Can you type instead of using 'as' keyword here!

2021-03-24 13:46 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +        actionOnUser: 'user',
actionOnUser: 'user' sounds suspicious here!
rigth?

2021-03-24 13:46 UTC, ClaudeROSSI commented on test/api/BillingStripeIntegrationTest.ts
> +        await testData.retrieveDeletedPaymentMethod();
method name is confusing:
i would suggest:
checkPaymentMethodDeletion ...

or I would group the two calls (68 et 69) in a single one and call it checkDetachPaymentMethod()

2021-03-24 15:14 UTC, ClaudeROSSI requested changes
ok - approved.

A few tests added + some minor changes

2021-03-24 15:15 UTC, ClaudeROSSI approved these changes

2021-03-24 21:37 UTC, cabch commented on src/integration/billing/stripe/StripeBillingIntegration.ts
>      const taxes = [] as BillingTax[];
done

2021-03-25 12:53 UTC, ClaudeROSSI approved these changes

2021-03-25 21:10 UTC, merged