Crypto migration task
sap-labs-france/ev-server pull request #2225
Opened 2021-03-25 07:46 UTC by roxiciobotea210

Add task for changing encryption key in case it matches the historical one.
* get both keys & compare them
* if they match, generate a new key with the default algorithm
* update key settings
* migrate encrypted data to new key

2021-03-25 08:06 UTC, jerome-benoit requested changes
It should be a migration task, not a scheduler task. That's probably because I've not tell you where exactly to add it ;)
That's not difficult to make it a migration task. 
Otherwise looks good to me.

2021-03-25 08:10 UTC, roxiciobotea210 commented
> It should be a migration task, not a scheduler task. That's probably because I've not tell you where exactly add it ;)
> That's not difficult to make it a migration task.
> Otherwise looks good to me.

Ah, sorry, I created it following the example of the scheduler task Stefania created and that's why I added it here. Will change it to migration, thanks! :)

2021-03-25 14:21 UTC, jerome-benoit commented on src/migration/tasks/ChangeCryptoKeyTask.ts
> +      // migrate sensitive data to the new key
Nitpick: comment should start with an upper case letter.

2021-03-25 14:21 UTC, jerome-benoit approved these changes

2021-03-26 17:19 UTC, LucasBrazi06 approved these changes
GUT!

2021-03-26 17:19 UTC, merged