REST > Added ChargingProfile get / update / delete validation
sap-labs-france/ev-server pull request #2368
Opened 2021-04-22 07:54 UTC by Ninjeneer

2021-04-22 08:03 UTC, jerome-benoit commented
@OliveGerste: since you're the smart charging expert ;), could you please review that PR and then promote it for a final review once ok? 

Thanks.

2021-04-22 16:08 UTC, OliveGerste requested changes
Hi Loan, good job so far.
Unfortunately we have a problem with the ChargingProfileID here. 
The validation is expecting an object ID, but the charging profiles are currently saved with a generated and hashed id from the storage method, which do not match the patterns.
Maybe we need a second opinion how to proceed here.

2021-04-23 14:38 UTC, Ninjeneer commented
As discussed, refactored and factorized the code of create and update charging profiles

2021-04-26 11:54 UTC, Ninjeneer commented on src/server/rest/v1/validator/ChargingStationValidator.ts
> +    this.validate(this.chargingProfileCreate, data);
Fixed

2021-05-06 14:52 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/chargingstation/chargingprofile-create.json
> +          "type": "string",
Enum: ChargePointMaxProfile, TxDefaultProfile, TxProfile

2021-05-06 14:52 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/chargingstation/chargingprofile-create.json
> +          "type": "string",
Enum: Ansolute, Reccuring, Relative

2021-05-06 14:52 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/chargingstation/chargingprofile-create.json
> +          "type": "string",
Enum: Daily, Weekly

2021-05-06 14:52 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/chargingstation/chargingprofile-create.json
> +              "type": "string",
Enum: W, A

2021-05-06 14:52 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/chargingstation/chargingprofile-create.json
> -  "$ref": "chargingstation.json#/definitions/chargingProfile"
Is it possible to reuse the profile structure from the definition somehow?
The only thing, which differs is that the id is mandatory right?

I also added some enums of the values which are possible for the different cp properties

2021-05-06 14:52 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/chargingstation/chargingprofile-create.json
> +      "type": "number",
The connector ID is reused. Is there a reason, that the cchargePoint ID is not reused?

2021-05-10 18:25 UTC, jerome-benoit commented
@OliveGerste: The status of that PR is still 'Request changes'?

2021-05-11 09:56 UTC, jerome-benoit commented
> > @OliveGerste: The status of that PR is still 'Request changes'?
> 
> I think it is not ready yet for a review is it?

I do not know, you're its main reviewer ;)

2021-05-13 16:07 UTC, merged