Update readme
sap-labs-france/ev-server pull request #2383
Opened 2021-04-27 15:50 UTC by roiko

Added useful configuration information that were missing

2021-04-27 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=2383) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=2383) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-labs-france/ev-server?pullRequest=2383) it.</sub>

2021-04-27 15:59 UTC, jerome-benoit requested changes

2021-04-27 15:59 UTC, jerome-benoit commented on README.md
> +    "database" : "evse"
`database` replace `schema` configuration key.

2021-04-28 14:16 UTC, LucasBrazi06 approved these changes
Gut!

2021-04-28 14:16 UTC, merged