Tags csv import back
sap-labs-france/ev-server pull request #2427
Opened 2021-05-12 08:56 UTC by cabch

2021-05-14 09:02 UTC, ClaudeROSSI requested changes
Please call me to discuss my comments.

2021-05-14 09:02 UTC, ClaudeROSSI commented on src/utils/Utils.ts
>      return typeof value === 'string' ? '"' + value.replace(/^"|"$/g, '').replace(/"/g, '""') + '"' : value;
I was expecting that this method also encodes the comma, etc ...
to make sure a value like "Yes, we can" can be imported.

2021-05-14 09:13 UTC, ClaudeROSSI commented
Why don't we rely on something like:
https://github.com/mafintosh/csv-parser

2021-05-17 12:31 UTC, cabch commented on src/utils/Utils.ts
>      return typeof value === 'string' ? '"' + value.replace(/^"|"$/g, '').replace(/"/g, '""') + '"' : value;
as we double quote the csv values to handle the comma inside a row value, here we double the double quotes so they are considered as simple double quotes when we display the value in excel for example

2021-05-17 12:57 UTC, cabch commented on src/utils/Utils.ts
> +  public static escapeCsvValues(value: any): string {
renamed ✅

2021-05-17 12:57 UTC, cabch commented on src/utils/Utils.ts
> +  public static unEscapeCsvValues(value: any): string {
modified ✅

2021-05-17 12:58 UTC, cabch commented on src/utils/Utils.ts
>      return typeof value === 'string' ? '"' + value.replace(/^"|"$/g, '').replace(/"/g, '""') + '"' : value;
And like that, no need to specifically handle the csv separator as it is inside the double quotes

2021-05-18 10:10 UTC, cabch commented on src/async-task/tasks/TagsImportAsyncTask.ts
> +                await this.assignTag(tenant, importedTag, tag);
done ✅

2021-05-19 10:34 UTC, jerome-benoit commented
@cabch: Could you please sync with master-qa branch and ensure the unit tests are run successfully on GitHub ? 

Thanks.

2021-05-19 10:35 UTC, jerome-benoit commented
@roxiciobotea210: Could you please sync with master-qa branch and ensure the unit tests are run successfully on GitHub ? 

Thanks.

2021-05-19 11:40 UTC, ClaudeROSSI requested changes
Please check my comments

2021-05-19 11:40 UTC, ClaudeROSSI commented on src/async-task/tasks/TagsImportAsyncTask.ts
> +            } // Do we add a finally that delete tags if the error comes from "foundTag" ? for now the found tags are left as is in the importedTag collection
Let's stick to the import of users logic. No finally required!
The error is for now simply stored (on line 93). That way we know that the import of a particular tag failed or not.
I guess we will introduce later a UI to cleanup all tags in errors

2021-05-19 11:40 UTC, ClaudeROSSI commented on src/async-task/tasks/TagsImportAsyncTask.ts
> +            } // Do we add a finally that delete tags if the error comes from "foundTag" ? for now the found tags are left as is in the importedTag collection
i think you can remove this comment then

2021-05-19 11:40 UTC, ClaudeROSSI commented on src/server/rest/v1/service/TagService.ts
> +        newImportedTag.email = '';
i think it makes sense to log the error here (maybe as a warning ...)

2021-05-19 11:40 UTC, ClaudeROSSI commented on src/storage/mongodb/TagStorage.ts
> +      email: Utils.unescapeCsvValue(importedTagToSave.email),
I think calling the unescape here this is not correct.

You do not know if you have to unescape because the property values may come either from the importedTag or from the existing tag (already unescaped).

The unescape must be done by the calling layer:
at the beginning of the for loop:
>> for (const importedTag of importedTags.result) {

2021-05-19 11:40 UTC, ClaudeROSSI commented on src/storage/mongodb/TagStorage.ts
> +      email: Utils.unescapeCsvValue(importedTagToSave.email),
idem. Please call me ;)

2021-05-19 11:40 UTC, ClaudeROSSI commented on src/utils/Utils.ts
> +    return typeof value === 'string' ? value.replace(/^"|"$/g, '').replace(/""/g, '"') : value;
to be on the safe side i would suggest to throw an exception when a string value does not start and end with a double quote.
This should not happen. If this happens, it means that the calling layer is trying to unescape something which was not escaped properly. This will produce unpredictable results.

2021-05-19 19:35 UTC, cabch commented on src/utils/Utils.ts
> +    return typeof value === 'string' ? value.replace(/^"|"$/g, '').replace(/""/g, '"') : value;
in fact starting and ending double quotes are handled by the csvToJson during import so at that Utils.unescapeCsvValue time there is no more double quotes at the begining and at the end

2021-05-19 19:35 UTC, cabch commented on src/storage/mongodb/TagStorage.ts
> +      email: Utils.unescapeCsvValue(importedTagToSave.email),
done ✅

2021-05-19 19:35 UTC, cabch commented on src/storage/mongodb/TagStorage.ts
> +      email: Utils.unescapeCsvValue(importedTagToSave.email),
you're right ✅

2021-05-19 19:35 UTC, cabch commented on src/server/rest/v1/service/TagService.ts
> +        newImportedTag.email = '';
done ✅

2021-05-19 19:35 UTC, cabch commented on src/async-task/tasks/TagsImportAsyncTask.ts
> +            } // Do we add a finally that delete tags if the error comes from "foundTag" ? for now the found tags are left as is in the importedTag collection
ok ✅

2021-05-19 20:15 UTC, cabch commented
> @cabch: Could you please sync with master-qa branch and ensure the unit tests are run successfully on GitHub ?
> 
> Thanks.

Would have been glad to do it by myself ;) sounds like it's ok now on GitHub

2021-05-20 07:08 UTC, ClaudeROSSI commented on src/utils/Utils.ts
> +    // starting and ending double quotes are handle by csvToJson
Do you mean that csvToJson already unescape the values? 
That would be good, but then there is no need to unescape values anymore.

To be on the safe side, we need to make sure the logic used during the export is compliant with the one csvToJon() applies when unescaping.

2021-05-20 07:10 UTC, ClaudeROSSI reviewed
we need to clarify what logic cvsToJson applies when converting imported values

2021-05-20 08:02 UTC, cabch commented on src/utils/Utils.ts
> +    // starting and ending double quotes are handle by csvToJson
yes csvtojson already escape by default double quotes at the beginning and the end.

the reason why we need to keep unescaping is for replacing the double double quote by simple double quotes

2021-05-20 10:10 UTC, ClaudeROSSI commented on src/utils/Utils.ts
> +    // starting and ending double quotes are handle by csvToJson
ok. unescapeCsvValue() does nothing because the csvToJson lib does it for us.

2021-05-20 10:11 UTC, ClaudeROSSI approved these changes

2021-05-20 10:11 UTC, merged