[2/3] Create Tag with visualID/ adapt unit test tags
sap-labs-france/ev-server pull request #2452
Opened 2021-05-19 15:07 UTC by mahdibenromdhane

2021-05-19 17:07 UTC, jerome-benoit commented
@mahdibenromdhane: Your plugins on vscode that should lint and fix the code are not properly configured. Please fix your setup and run `npm run eslint:fix` on your work branches.

2021-05-20 08:47 UTC, mahdibenromdhane commented
> @mahdibenromdhane: Your plugins on vscode that should lint and fix the code are not properly configured. Please fix your setup and run `npm run eslint:fix` on your work branches.

Done.

2021-05-20 08:53 UTC, jerome-benoit requested changes

2021-05-20 08:53 UTC, jerome-benoit commented on src/server/rest/v1/service/TagService.ts
> +        message: `Tag with ID '${filteredRequest.id}' already exists`,
The error message is misleading: you look for for duplicate visualID records and the message is refereeing to the tag id.

2021-05-20 08:53 UTC, jerome-benoit commented on src/server/rest/v1/service/TagService.ts
> +            // eslint-disable-next-line @typescript-eslint/no-misused-promises
Previous indentation was correct.

2021-05-20 08:53 UTC, jerome-benoit commented on src/server/rest/v1/service/TagService.ts
> +            // eslint-disable-next-line @typescript-eslint/no-misused-promises
Previous indentation was correct.

2021-05-20 08:53 UTC, jerome-benoit commented on src/storage/mongodb/TagStorage.ts
> +        withUser?: boolean; withUsersOnly?: boolean; withNbrTransactions?: boolean; search?: string, defaultTag?: boolean, active?: boolean, visualID?: string[]
The added argument naming and ordering is inconsistent: 
Please create an helper method `getTagByVisualIDs`, rename `visualID?` to `visualIDs?` and put `visualIDs?` param after `userIDs?`

And reuse `getTagByVisualIDs` in `getTagByVisualID`

2021-05-20 13:48 UTC, jerome-benoit approved these changes

2021-05-20 13:48 UTC, merged