Billing - stripe - country code in addresses
sap-labs-france/ev-server pull request #2466
Opened 2021-05-24 08:00 UTC by ClaudeROSSI

Stripe expects a Two-letter country code (ISO 3166-1 alpha-2)

- The country entered in the address of the customer is converted to the Alpha 2 code when creating/updating the corresponding data on the stripe side.
- Same logic applies when creating a payment method. The billing details information attached to the card information benefit from the same country code conversion logic.

**Known restriction**: The end user must provide the country name in his/her locale. In other words, entering Germany, when  your language is 'de', is not supported. A German end-user has to enter 'Deutschland' instead!

2021-05-24 08:03 UTC, ClaudeROSSI commented
Example of billing details with proper country code information:
![image](https://user-images.githubusercontent.com/26900551/119316408-35857180-bc77-11eb-809a-a02a02828fd5.png)

2021-05-25 09:06 UTC, jerome-benoit commented on src/integration/billing/stripe/StripeHelpers.ts
> +        countryCode = Countries.getAlpha2Code(countryName, Constants.DEFAULT_LANGUAGE); // converts 'Germany' to 'DE' when lang is 'en'
The comment is not accurate.

2021-05-25 13:00 UTC, cabch commented
error occured when creating a payment method when user has no adress at all

2021-05-25 13:02 UTC, cabch requested changes
error occured when creating a payment method when user has no adress at all

2021-05-25 13:54 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeHelpers.ts
> +        countryCode = Countries.getAlpha2Code(countryName, Constants.DEFAULT_LANGUAGE); // converts 'Germany' to 'DE' when lang is 'en'
done
// Fallback - try it again with the default language

2021-05-25 13:56 UTC, ClaudeROSSI commented
> error occurred when creating a payment method when user has no adress at all

Problem solved.
STRIPE does not accept:
> {
>   address: null
> }

code fixed and made safer!

2021-05-26 08:50 UTC, jerome-benoit approved these changes
Mergeable for rc2. 

@ClaudeROSSI: did you have a look at the code in OCPI to get alpha3 code? It might be inspirational. 

@LucasBrazi06: Ok to merge it and deploy on QA with the rc2?

2021-05-26 12:47 UTC, merged

2021-05-26 14:05 UTC, cabch commented
error occured when creating a payment method when user has no country in address