Start transaction - check payment method
sap-labs-france/ev-server pull request #2573
Opened 2021-06-17 15:24 UTC by ClaudeROSSI

Preparing the server in order to make it possible to prevent a start transaction when the billing prerequisites are not met.

**New enum** 

> enum **StartTransactionCheck** {
>   OK = 'ok',
>   BILLING_NO_PAYMENT_METHOD = 'no_payment_method',
>   BILLING_NO_TAX = 'billing_no_tax', 
>   BILLING_NO_SETTINGS = 'billing_no_settings', 
>   BILLING_INCONSISTENT_SETTINGS = 'billing_inconsistent_settings',
> }

The UI will enable the start transaction button only when the check status is set to **StartTransactionCheck.OK**

The status is send together with the Tag and the Car when using the endpoint **getUserDefaultTagCar** endpoint.

2021-06-18 13:39 UTC, LucasBrazi06 requested changes

2021-06-18 13:39 UTC, LucasBrazi06 commented on src/server/rest/v1/service/UserService.ts
> +    res.json({ tag, car, status });
As discussed, return an array of enum

2021-06-21 05:40 UTC, ClaudeROSSI commented
@LucasBrazi06 : Changes have been done

 
![image](https://user-images.githubusercontent.com/26900551/122712247-e6c1fc00-d263-11eb-9256-451a62026b09.png)

2021-06-21 07:49 UTC, LucasBrazi06 approved these changes

2021-06-21 07:50 UTC, merged