Data transfer   back
sap-labs-france/ev-server pull request #2704
Opened 2021-07-29 17:13 UTC by rmangin-fr

Do not merge this !
Should I copy OCPPDataTransferStatus stuff into OCPPClient ?

2021-07-29 17:20 UTC, rmangin-fr commented on src/client/ocpi/OCPIChargingStationClient.ts
> +import { OCPPDataTransferRequest, OCPPDataTransferResponse } from '../../types/ocpp/OCPPServer';
@LucasBrazi06: I need your advise, I'm not sure if I should copy definitions into the Client file ?

2021-08-04 09:46 UTC, ClaudeROSSI requested changes
as discussed, please mimic the logic of other commands

2021-08-04 09:46 UTC, ClaudeROSSI commented on src/client/ocpi/OCPIChargingStationClient.ts
> +import { OCPPDataTransferRequest, OCPPDataTransferResponse } from '../../types/ocpp/OCPPServer';
as discussed, please mimic what is done for other the commands. Dedicated interfaces have to be defined

2021-08-24 16:37 UTC, rmangin-fr commented
Need to test on QA

2021-08-25 15:17 UTC, LucasBrazi06 approved these changes
GOOD JOB!!!

2021-08-25 15:18 UTC, merged