Split endpoints
sap-labs-france/ev-server pull request #2713
Opened 2021-08-03 08:33 UTC by rmangin-fr

2021-08-05 20:13 UTC, LucasBrazi06 commented
@Ninjeneer @ClaudeROSSI Could you review this PR?

2021-08-06 01:51 UTC, Ninjeneer requested changes

2021-08-06 01:51 UTC, Ninjeneer commented on src/assets/server/rest/v1/schemas/chargingstation/chargingstation-action-start-transaction.json
> +          "type": "string",
You can use the $ref for the id in the tag.json definition

2021-08-06 01:51 UTC, Ninjeneer commented on src/assets/server/rest/v1/schemas/chargingstation/chargingstation-action-start-transaction.json
> +          "type": "string",
Same for the visual ID

2021-08-06 10:59 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/chargingstation/chargingstation-action-start-transaction.json
> +          "$ref": "tag.json#/definitions/visualID"
i think visual ID and tagID have a different type!
I'm not sure which format is expected here!

2021-08-06 11:09 UTC, Ninjeneer requested changes

2021-08-06 11:09 UTC, Ninjeneer commented on src/assets/server/rest/v1/schemas/chargingstation/chargingstation-action-start-transaction.json
> +          "$ref": "tag.json#/definitions/visualID"
id here, not visualID :)

2021-08-25 12:29 UTC, rmangin-fr commented
Tested with OK on IOS 12.5 (Simulation) with local tenant DALI

2021-09-01 13:38 UTC, LucasBrazi06 commented
@rmangin-fr Your PR is in Requested Change pipeline !!!

2021-09-01 14:33 UTC, LucasBrazi06 approved these changes

2021-09-01 14:33 UTC, LucasBrazi06 commented on src/assets/server/rest/v1/schemas/chargingstation/chargingstation-action-start-transaction.json
> +        "tagID": {
@rmangin-fr Do not close the conversation otherwise I cannot check ;-)

2021-09-01 14:33 UTC, merged