When charging stations in site are public, throw error if site is made private
sap-labs-france/ev-server pull request #2742
Opened 2021-08-18 11:58 UTC by RohanAntony

2021-08-23 07:53 UTC, RohanAntony commented
Do I need to log the Error?

2021-08-23 14:16 UTC, LucasBrazi06 commented
> Do I need to log the Error?
Normally, when you throw the exception, it should be already logged.

2021-09-01 13:45 UTC, LucasBrazi06 requested changes

2021-09-01 13:45 UTC, LucasBrazi06 commented on src/server/rest/v1/service/SiteService.ts
> +          { siteIDs: [site.id], public: true, withSiteArea: true }, Constants.DB_PARAMS_MAX_LIMIT)).result;
Limit to one charging stations and project only the charging station's ID

2021-09-01 13:46 UTC, LucasBrazi06 commented
Like the other issue, create an issue + link your PR to it + paste the link in Asana.

2021-09-02 09:10 UTC, RohanAntony commented
@LucasBrazi06 While throwing the AppError, why do we not see the message in the notification that pops up? It seems like a longer process if the user has to go to the logs and read the message.

2021-09-02 09:27 UTC, LucasBrazi06 commented
> @LucasBrazi06 While throwing the AppError, why do we not see the message in the notification that pops up? It seems like a longer process if the user has to go to the logs and read the message.

You have to catch the exception in the front-end and display an i18n message ;-) so I would expect a PR in the dashboard also.

2021-09-02 20:15 UTC, LucasBrazi06 commented
@RohanAntony  Still not attached to an issue, just did it.

2021-09-02 20:25 UTC, LucasBrazi06 requested changes
You have also to check when you set a charging station public on a non-public site.

2021-09-02 20:25 UTC, LucasBrazi06 commented on src/server/rest/v1/service/SiteService.ts
> +        const publicChargingStation = await ChargingStationStorage.getPublicChargingStationInSite(req.tenant, {
No need to create a specific method in Storage for this you can call the method right away.

2021-09-07 06:25 UTC, LucasBrazi06 approved these changes
Ok, still charging station to handle

2021-09-07 06:38 UTC, merged