Add additional ids such as siteID, siteAreaID, companyID and chargingStationID to logs for site admin
sap-labs-france/ev-server pull request #2762
Opened 2021-09-01 11:09 UTC by RohanAntony

Adding siteID, siteAreaID, companyID and chargingStationID which will be used during getLogs in later PR to fetch data. This will replace the operation of fetching siteID based on chargingStationIDs and instead use the siteID available in the logs directly.

2021-09-01 11:13 UTC, RohanAntony commented
@LucasBrazi06 In the final commit, I have populated the siteID, siteAreaID and companyID in WSConnection.ts file assuming the URL has the values. The discussion on the mail stated that we are fetching the chargingStation object from DB using the chargingStationID but there is no use of ChargingStationStorage in WSConnection. 

Should I keep the approach of fetching data from the URL or change it and add a DB call to fetch the appropriate charging station and populate the fields?

2021-09-01 12:51 UTC, LucasBrazi06 commented
> The discussion on the mail stated that we are fetching the chargingStation object from DB using the chargingStationID but there is no use of ChargingStationStorage in WSConnection.

It's because it's in its sub-class JsonWSConnection ;-)

2021-09-01 13:42 UTC, LucasBrazi06 commented
@RohanAntony Create an issue in GitHub and link all of your PR to it.
Put the issue's link into the Asana task.

2021-09-01 14:28 UTC, LucasBrazi06 requested changes

2021-09-01 14:28 UTC, LucasBrazi06 commented on src/server/ocpp/json/JsonCentralSystemServer.ts
> +  public getChargingStationClient(tenantID: string, chargingStationDetails: {
I would have prefered the location data in an dedicated optional param:
```
public getChargingStationClient(tenantID: string, chargingStationID: string,
  chargingStationLocation?: { siteID: string, siteAreaID: string, companyID: string }) {
```
or
```
public getChargingStationClient(tenantID: string, chargingStationID: string,
  siteID?: string, siteAreaID?: string, companyID?: string) {
```

2021-09-02 10:51 UTC, RohanAntony commented
@LucasBrazi06 In the last commit that was pushed a while back, I have made changes to logging.ts and other files related to it. I ran the test cases on my local machine which covers all of them except OCPP 1.6 service test case. This has been consistently failing on my machine for every branch including master-qa. I don't know on how else to test these latest changes except for the test cases.

2021-09-02 10:51 UTC, RohanAntony commented
I believe, I need to make changes to AppError and BackendError which also get logged.

2021-09-02 12:11 UTC, LucasBrazi06 commented
@RohanAntony I can check the unit test on my side if you want on your branch?

2021-09-02 12:12 UTC, LucasBrazi06 commented
> I believe, I need to make changes to AppError and BackendError which also get logged.

AppError is for HTTP Service endpoint (REST, OCPI...), the rest is BackendError.

2021-09-02 20:19 UTC, merged

2021-09-02 21:11 UTC, LucasBrazi06 commented
@RohanAntony I just added the most important part you missed + conversion to ObjectIDs :-)
![2021-09-02_23-09-59.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/1402202d-5c58-4f5e-86d1-91fc84bbaf4a)

2021-09-02 22:18 UTC, LucasBrazi06 commented
@RohanAntony I think you missed the Exception that are also logged:
![2021-09-03_00-15-17.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/dfdb74f1-7234-4cc7-8831-065f63a32a42)
![2021-09-03_00-17-33.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/4b571122-856a-45a2-aab6-bf1b51ec9454)
I'll put back the issue to In Process ;-).

2021-09-06 08:15 UTC, RohanAntony commented
> @RohanAntony I just added the most important part you missed + conversion to ObjectIDs :-)
> ![2021-09-02_23-09-59.png](https://camo.githubusercontent.com/6f5ab1d1b43fadfa9ff0afbb99613ade18be9be774e8b0a2bba607fbcc8c6a4b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564666366386365663533383862646337393230303764662f31343032323032642d356335382d346635652d383664312d393166633834626261663461)

Do we not need to add it for chargingStationID which is also an ObjectID?

2021-09-06 08:19 UTC, LucasBrazi06 commented
> Do we not need to add it for chargingStationID which is also an ObjectID?

No, Charging Station ID is a string in the DB.
You can check this with the Storage classes or with Robot3T.