add tariffID in OCPI settings
sap-labs-france/ev-server pull request #2961
Opened 2021-10-14 15:33 UTC by rmangin-fr

2021-11-04 13:31 UTC, rmangin-fr commented on src/server/rest/v1/service/SettingService.ts
> +        filteredRequest = settingUpdate;
done :)

2021-11-08 10:27 UTC, ClaudeROSSI requested changes
does not compile anymore.

check my comments

2021-11-08 10:27 UTC, ClaudeROSSI commented on src/server/rest/v1/service/SettingService.ts
>          if (Utils.hash(settingUpdate.content.crypto.key) !== Utils.hash(setting.content.crypto.key)) {
settingUpdate ... 
does not compile!

2021-11-08 10:46 UTC, ClaudeROSSI approved these changes

2021-11-16 00:11 UTC, LucasBrazi06 commented
@rmangin-fr Conflicting files.

2021-11-16 13:21 UTC, LucasBrazi06 approved these changes

2021-11-16 13:22 UTC, merged