REST > Settings getMany/getByIdentifier/getOne/create endpoints + doc
sap-labs-france/ev-server pull request #3074
Opened 2021-11-17 14:17 UTC by Ninjeneer

2021-11-17 16:03 UTC, ClaudeROSSI commented
> @ClaudeROSSI Could you please check this one?

je regardes ca now

2021-11-17 17:14 UTC, ClaudeROSSI requested changes
billing tests are failing:

please have a look to my comments

2021-11-17 17:14 UTC, ClaudeROSSI commented on test/api/client/SettingApi.ts
> +    return super.readAll(params, paging, ordering, this.buildRestEndpointUrl(ServerRoute.REST_SETTINGS));
Hi,

I have some billing tests that are not running properly anymore.
Please have a look to the screenshot below.
The billing tests are forcing the billing settings using the REST endpoints ... it seems that readdall does not return the expected data.

![Screenshot from 2021-11-17 18-09-45](https://user-images.githubusercontent.com/26900551/142248502-e89bef19-bc68-4cad-ab95-6daa405792ab.png)

Please do not forget:
- to create the test context again (npm run mochatest:createContext)
- to refresh the test list (the billing tests have been reorganized recently).

2021-11-18 21:30 UTC, LucasBrazi06 commented
@ClaudeROSSI To be rechecked I think.
Thanks!!!

2021-11-19 11:03 UTC, ClaudeROSSI reviewed
@Ninjeneer : Smart Charging Tests are not running.

They are all green when using the master branch. 
Can you double check?

2021-11-19 11:04 UTC, ClaudeROSSI commented
@Ninjeneer : Smart charging tests are failing after merging the master-qa branch

![Screenshot from 2021-11-19 12-03-42](https://user-images.githubusercontent.com/26900551/142612394-abcea242-0ad9-4f35-8cd2-2e9338836ca7.png)

please couble check.
Thanks
Claude

2021-11-19 13:12 UTC, ClaudeROSSI approved these changes
All tests are now running properly

2021-11-19 14:19 UTC, LucasBrazi06 commented
> All tests are now running properly

Thanks Claude!!!

2021-11-19 14:19 UTC, merged