Refuse create/update unknown settings
sap-labs-france/ev-server pull request #3157
Opened 2021-12-09 14:25 UTC by Ninjeneer

Also added missing `bakcupSensitiveData` attribute in every setting schemas

2021-12-09 14:40 UTC, LucasBrazi06 commented
@ClaudeROSSI Could you check this one?
Thanks!

2021-12-10 15:30 UTC, ClaudeROSSI requested changes
I have some comments.

Please let me know what you think.
I won't push the changes that we discussed and that I did on my side.

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/assets/schemas/setting/setting.json
> +    "backupSensitiveData": {
As far as I know **backupSensitiveData** is never used client-side.
I therefore do not see why it should be visible in our REST API.

From my perspective, we should just skip this information to make sure the POST/PUT request cannot override this critical information.
@LucasBrazi06 : Do we have a use-case where the backup of the sensitive data has to be manipulated thru a REST API?

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/setting/setting-analytics-set.json
> +    "backupSensitiveData": {
same comment

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/setting/setting-asset-set.json
> +    "backupSensitiveData": {
idem

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/setting/setting-organization-set.json
> +    "backupSensitiveData": {
idem

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/server/rest/v1/service/SettingService.ts
> +    const filteredRequest = SettingService.filterSetting(action, req) as SettingDB;
I do not think it make sense to cast as SettingDB here.
I would suggest that SettingService.**filterSetting** method has **SettingDB** as return type then.

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/server/rest/v1/service/SettingService.ts
> +    const filteredRequest = SettingService.filterSetting(action, req) as SettingDB;
idem

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/server/rest/v1/validator/SettingValidator.ts
>    public validateSettingCarConnectorSetReq(data: Record<string, unknown>): HttpSettingCarConnectorSetRequest {
The return type should be SettingDB

2021-12-10 15:30 UTC, ClaudeROSSI commented on src/server/rest/v1/validator/SettingValidator.ts
> +  public validateSettingCarSetReq(data: Record<string, unknown>) {
As discussed on the phone the return type should be SettingDB for all methods.
And all HttpSetting*interface (added by Remi) are then from my perspective useless!
@LucasBrazi06 : We have new interfaces that are never used (such as **HttpSettingCarConnectorSetRequest**) ... I'm not sure why they have been added!

2021-12-10 15:30 UTC, ClaudeROSSI commented on test/api/SettingTest.ts
> +        let update = await testData.centralService.settingApi.update(read.data);
This update does nothing because the type si by default set to 'simple' when using the **utall** tenant.
do you agree?

2021-12-19 16:11 UTC, LucasBrazi06 commented
@ClaudeROSSI Need your approval

2021-12-19 16:11 UTC, LucasBrazi06 commented
Moved to dev-cross-review

2021-12-19 16:13 UTC, LucasBrazi06 commented
@ClaudeROSSI My bad, made mistake on the wrong pipeline :-(, I just put in back in requested change.

2021-12-20 07:59 UTC, Ninjeneer commented on test/api/SettingTest.ts
> +        let update = await testData.centralService.settingApi.update(read.data);
Yep ! 
Switched from 'simple' to 'convergentCharging' for test

2021-12-20 08:29 UTC, Ninjeneer commented on src/assets/schemas/setting/setting.json
> +    "backupSensitiveData": {
You're right, it isn't sent from the client side. 
I removed every "backupSensitiveData" in schemas

2021-12-20 08:32 UTC, Ninjeneer commented on src/server/rest/v1/service/SettingService.ts
> +    const filteredRequest = SettingService.filterSetting(action, req) as SettingDB;
Fixed, same for below comments

2021-12-22 09:29 UTC, ClaudeROSSI approved these changes
Approved.

But I think we can have get rid of some interfaces which are not used anymore!
What do you think?

![image](https://user-images.githubusercontent.com/26900551/147069818-c2bb5112-04b1-4483-9bb6-32937b5730fc.png)

2021-12-22 15:39 UTC, Ninjeneer commented
> Approved.
> 
> But I think we can have get rid of some interfaces which are not used anymore! What do you think?
> 
You're right, I removed it. We can still retrieve it from the Git history in case we need it later.

2022-01-03 09:21 UTC, merged