Pricing - price extra inactivity
sap-labs-france/ev-server pull request #3230
Opened 2022-01-06 23:22 UTC by ClaudeROSSI

**pricing of the extra inactivity**

- billing not done on STOP transaction anymore
- Transaction.END is now used to trigger the invoice generation!

2022-01-07 14:17 UTC, ClaudeROSSI commented
I have some doubts about this PR. The changes are very sensitive to the connector status and to the corresponding OCPP status notifications. 
What happens if we restart some server processes while transactions are in progress? 

**Billing changes** are the ones below:
1) the billing module does not trigger the billing task on a STOP transation anymore.
It now simply puts the transaction.billingData.stop.status to **Billing.PENDING**!
2) the actual billing async task is now only created when the extra inactivity is computed.
The billing module expects to be called with a **Transaction.END** action (and not **Transaction.STOP**). 
3) Checks have been added to make sure we do not trigger this twice
4) billing data thresholds are only checked during the STOP transaction

Pricing changes:
1) A final call to the PricingEngine is made when computing the extra inactivity.
Method: OCPPUtils.**checkAndUpdateLastCompletedTransaction**() 
2) PricingEngine will create chunks to properly price the final consumption but this is part of another PR.

2022-01-07 14:45 UTC, LucasBrazi06 commented
> What happens if we restart some server processes while transactions are in progress?

The charger should resume the meter values which it was not able to send.

2022-01-07 14:48 UTC, LucasBrazi06 commented
> I have some doubts about this PR. The changes are very sensitive to the connector status and to the corresponding OCPP status notifications.

We also need to add a Job when no Status Notification have been sent. Like the CDR.

2022-01-07 15:36 UTC, ClaudeROSSI commented
> > I have some doubts about this PR. The changes are very sensitive to the connector status and to the corresponding OCPP status notifications.
> 
> We also need to add a Job when no Status Notification have been sent. Like the CDR.

right

2022-01-10 14:10 UTC, ClaudeROSSI commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                      'billingData.stop.status': BillingStatus.PENDING
@mahdibenromdhane : as discussed, my job is looking for transactions where the Transaction.STOP has been received but the extra inactivity is unknown (extraInactivityComputed===false). In other words, the OCPP notification regarding connector the connector availability has not been processed.
In that case I need to price the last consumption and trigger the billing.
Your use-case where you need to stop "ghost sessions" is from my perspective similar (and needs to be priced as well). We therefore need to be in sync regarding the logic on how to detect old transactions. Maybe a single job would be sufficient for both use-cases.

2022-01-10 15:23 UTC, LucasBrazi06 requested changes
Check my comments

2022-01-10 15:23 UTC, LucasBrazi06 commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                        if (connector.status !== ChargePointStatus.AVAILABLE) {
Do not check the connector's status but it's transaction ID:
`      if (connector.currentTransactionID === transaction.id) {`

2022-01-10 15:23 UTC, LucasBrazi06 commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                        }
Nothing to do with closing an opened transaction

2022-01-10 15:23 UTC, LucasBrazi06 commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                    // Release the lock
Wrong Indentation (WI)

2022-01-10 15:23 UTC, LucasBrazi06 commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +            // Release the lock
WI

2022-01-10 15:23 UTC, LucasBrazi06 commented on src/server/ocpp/services/OCPPService.ts
> +                const lastConsumption = await OCPPUtils.buildExtraConsumptionInactivity(tenant, chargingStation, lastTransaction);
Just after the IF statement, is it possible to build methods like this.buildLastTransactionExtraInactivity(...) and put all that code in it to improve readability?

2022-01-10 15:23 UTC, LucasBrazi06 commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
Possible to put this call just before the first CDR call in line 845?

2022-01-10 15:30 UTC, ClaudeROSSI commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                        // Avoid conflict with a session which is still in progress
> Not possible as on going transaction does not have the 'stop' property.

But here I'm trying to detect the situation where the stop has been received but the car is still plugged to the charging station. So for me the transaction is still on-going because the extra inactivity is not yet known.
Do you agree that I must handle it here?

2022-01-10 15:43 UTC, LucasBrazi06 commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                        // Avoid conflict with a session which is still in progress
Okay I got it, so it's fine!

2022-01-10 16:21 UTC, ClaudeROSSI commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
> Possible to put this call just before the first CDR call in line 845?

I do not feel confortable. 
If we move it we then take the risk to call several times the billing process.
Are we sure "**checkAndUpdateLastCompletedTransaction**" is never called twice?

2022-01-10 16:23 UTC, LucasBrazi06 commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
Be sure that you handle this use case in the billing ;-)

2022-01-10 16:33 UTC, ClaudeROSSI commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
> Be sure that you handle this use case in the billing ;-)

I billing handles it. It throws an exception. What about the calling layer? 
What shall we do if the billing rejects a second call?

2022-01-10 16:36 UTC, ClaudeROSSI commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                      'billingData.stop.status': BillingStatus.PENDING
> Yes, only one job should trigger calculation of non existing extra inactivity that will trigger the CDR and the Billing. Mahdi's job about Ghost sessions is another use case, it's based on non existing 'stop' property and will not trigger the extra inactivity calculation if I'm not wrong.

You're right, Mehdi's job won't trigger the extra inactivity calculation. But then, if we stop the transaction without simulating the OCPP call changing the connector status, we will then have a transaction with no invoice! Right?

2022-01-10 16:37 UTC, LucasBrazi06 commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
If it throws an exception during a Status Notification it has no effect on the OCPP return call (always return an empty response).
In the end you will have only a log in error.
Whether add a try...catch and log a warning in the caller or remove the exception throw in the billing and log a warning.
As you want.

2022-01-10 16:44 UTC, ClaudeROSSI commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
> If it throws an exception during a Status Notification it has no effect on the OCPP return call (always return an empty response). In the end you will have only a log in error. Whether add a try...catch and log a warning in the caller or remove the exception throw in the billing and log a warning. As you want.

OK - I'll remove the exceptions - and log warnings when suspicious calls are detected on the billing side

2022-01-10 16:53 UTC, ClaudeROSSI commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
> > If it throws an exception during a Status Notification it has no effect on the OCPP return call (always return an empty response). In the end you will have only a log in error. Whether add a try...catch and log a warning in the caller or remove the exception throw in the billing and log a warning. As you want.
> 
> OK - I'll remove the exceptions - and log warnings when suspicious calls are detected on the billing side

well ... this is not possible! please call me!

2022-01-10 16:54 UTC, LucasBrazi06 commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                      'billingData.stop.status': BillingStatus.PENDING
Indeed, but your job's next run should see it and bill it ;-)

2022-01-10 16:55 UTC, LucasBrazi06 commented on src/server/ocpp/services/OCPPService.ts
> +            await OCPPUtils.processTransactionBilling(tenant, lastTransaction, TransactionAction.END);
We can discuss this tomorrow onsite ;-)

2022-01-10 16:57 UTC, ClaudeROSSI commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                      'billingData.stop.status': BillingStatus.PENDING
> Indeed, but your job's next run should see it and bill it ;-)

Right! This is the "cat pattern" ... cats always land on their feet lol

2022-01-11 08:04 UTC, ClaudeROSSI commented on src/integration/pricing/sap-convergent-charging/SapConvergentChargingPricingIntegration.ts
> +  public async endSession(transaction: Transaction, consumptionData: Consumption): Promise<PricedConsumption> {
@LucasBrazi06 : Convergent Charging - endSession has been added but not tested!

2022-01-11 08:05 UTC, ClaudeROSSI commented on src/integration/pricing/PricingIntegration.ts
> +  public abstract endSession(transaction: Transaction, consumptionData: Consumption, chargingStation?: ChargingStation): Promise<PricedConsumption>;
@LucasBrazi06 : I changed the pricing API to have both the stopSession, endSession method!

2022-01-11 08:06 UTC, ClaudeROSSI commented on src/server/ocpp/services/OCPPService.ts
> +                const lastConsumption = await OCPPUtils.buildExtraConsumptionInactivity(tenant, chargingStation, lastTransaction);
done

2022-01-11 08:07 UTC, ClaudeROSSI commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +            // Release the lock
ok

2022-01-11 08:07 UTC, ClaudeROSSI commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                    // Release the lock
ok

2022-01-11 08:07 UTC, ClaudeROSSI commented on src/scheduler/tasks/BillPendingTransactionTask.ts
> +                      const chargingStation = await ChargingStationStorage.getChargingStation(tenant, transaction.chargeBoxID);
done

2022-01-11 08:21 UTC, ClaudeROSSI commented
All tests are green!
Please review again ;) ... thanks

2022-01-11 18:58 UTC, ClaudeROSSI commented
Some Transaction tests are failing because of the chunk logic used when pricing.

Exemple below: 2 sessions of one hour, consuming only 1 kWh.
This generates 60 chunks with a very low consumption.
The accumulated amount (priced at 1 euro per kWh) loses some precision.

Here is the result: **totalPrice** is not the expected one!

<img width="467" alt="2022-01-11_19-53-45" src="https://user-images.githubusercontent.com/26900551/149004332-4c315918-59ca-43d4-92f5-16fad9786f9d.png">

I'm not sure we can fix that one!

2022-01-12 06:31 UTC, LucasBrazi06 commented
> I'm not sure we can fix that one!

Oups!
Is this a real use case?

2022-01-12 07:31 UTC, ClaudeROSSI commented
> > I'm not sure we can fix that one!
> 
> Oups! Is this a real use case?

Well ... real use-case or not, the root cause is the fact that we do not preserve the precision when storing the data in the DB.
c.f.: below an example reproducing the root cause:
- **totalPriceAsDecimal** is correct
- **totalPrice** is wrong and corresponds to what we do (since we convert to number the persisted data)

![image](https://user-images.githubusercontent.com/26900551/149082965-0a0e0e69-10e8-4475-87aa-770ea96bf801.png)

I'm investigation on how to persist the accumulated amount with its 'full' precision!

2022-01-12 09:12 UTC, LucasBrazi06 commented
> I'm investigating on how to **persist the accumulated amount** with its 'full' precision!

Okay.

2022-01-13 13:59 UTC, ClaudeROSSI commented
> > > I'm not sure we can fix that one!
> > 
> > 
> > Oups! Is this a real use case?
> 
> Well ... real use-case or not, the root cause is the fact that we do not preserve the precision when storing the data in the DB. I'm investigating on how to **persist the accumulated amount** with its 'full' precision!
> 
> c.f.: below an example reproducing the root cause:
> 
> * **totalPriceAsDecimal** is correct
> * **totalPrice** is wrong and corresponds to what we do (since we convert to number the persisted data)
> 
> ![image](https://user-images.githubusercontent.com/26900551/149082965-0a0e0e69-10e8-4475-87aa-770ea96bf801.png)

Problem solved by serializing the Decimal object instead of converting it to a number.
The Decimal object can be serialized and de-serialized thanks to some undocumented capabilities of the Decimal.js module.

2022-01-13 14:29 UTC, LucasBrazi06 approved these changes

2022-01-13 14:29 UTC, merged