REST > Billing getOne/getMany/Download/Webhook doc + schemas
sap-labs-france/ev-server pull request #3286
Opened 2022-01-25 09:39 UTC by Ninjeneer

\+ postman collection update

2022-01-25 15:46 UTC, ClaudeROSSI requested changes
The billing validator is not similar to the other ones (in term of naming).
Please check my comments and suggestion.

2022-01-25 15:46 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/billing/invoices-get.json
> +      "pattern": "^((paid|open|draft|void|uncollectible|deleted)(\\||paid|open|draft|void|uncollectible|deleted)*)?$",
The regex seems wrong to me!
Please have a look to my suggestion below:

```suggestion
      "pattern": "^((paid|open|draft|void|uncollectible|deleted)(\|paid|\|open|\|draft|\|void|\|uncollectible|\|deleted)*)?$",
```

2022-01-25 15:46 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    const filteredRequest = BillingValidator.getInstance().validateBillingInvoicesGetByIdReq(req.query);
Name is not similar to the one used by other validators

See my proposal:
```suggestion
    const filteredRequest = BillingValidator.getInstance().validateBillingInvoiceGetReq(req.query);
```

2022-01-25 15:46 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    const filteredRequest = BillingValidator.getInstance().validateBillingInvoicesGetByIdReq(req.query);
idem. Name is confusing:

```suggestion
    const filteredRequest = BillingValidator.getInstance().validateBillingInvoiceGetReq(req.query);
```

2022-01-25 15:46 UTC, ClaudeROSSI commented on src/server/rest/v1/service/security/BillingSecurity.ts
> +      TenantID: sanitize(requestQuery.TenantID)
Method is not used anymore.
Please remove it.

2022-01-25 15:46 UTC, ClaudeROSSI commented on src/server/rest/v1/validator/BillingValidator.ts
> +  private billingInvoiceGetByID: Schema = JSON.parse(fs.readFileSync(`${global.appRoot}/assets/server/rest/v1/schemas/billing/invoice-get-by-id.json`, 'utf8'));
file name is not similar to the others

suggestion:
invoice-get.json

please rename the corresponding file

2022-01-25 15:46 UTC, ClaudeROSSI commented on src/server/rest/v1/validator/BillingValidator.ts
> +  public validateBillingInvoicesGetReq(data: Record<string, unknown>): HttpBillingInvoiceRequest {
Name of the returned type is confusing. 
I would expect an "s"

```suggestion
  public validateBillingInvoicesGetReq(data: Record<string, unknown>): HttpBillingInvoicesRequest {
```

2022-01-25 15:46 UTC, ClaudeROSSI commented on src/server/rest/v1/validator/BillingValidator.ts
> +  public validateBillingInvoicesGetByIdReq(data: Record<string, unknown>): HttpBillingRequest {
Both the name of the method and name of the returned type are confusing

```suggestion
  public validateBillingInvoicesGetReq(data: Record<string, unknown>): HttpBillingInvoiceRequest {
```

2022-01-25 21:03 UTC, Ninjeneer commented on src/assets/server/rest/v1/schemas/billing/invoices-get.json
> +      "pattern": "^((paid|open|draft|void|uncollectible|deleted)(\\||paid|open|draft|void|uncollectible|deleted)*)?$",
Both work actually. The difference is that my pattern accept values such as `paid|` . Even if it as no really sense when it's written, this is actually a legit value, what do you think ?

2022-01-26 08:26 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/billing/invoices-get.json
> +      "pattern": "^((paid|open|draft|void|uncollectible|deleted)(\\||paid|open|draft|void|uncollectible|deleted)*)?$",
my understanding is that your pattern also accepts something like:
- paidpaiddraft
Does it?

2022-01-26 08:55 UTC, Ninjeneer commented on src/assets/server/rest/v1/schemas/billing/invoices-get.json
> +      "pattern": "^((paid|open|draft|void|uncollectible|deleted)(\\||paid|open|draft|void|uncollectible|deleted)*)?$",
Oh yes it does, nice catch :) There are missing parenthesis. I'll take yours then

2022-01-26 09:23 UTC, Ninjeneer commented on src/server/rest/v1/service/BillingService.ts
> +    const filteredRequest = BillingValidator.getInstance().validateBillingInvoicesGetByIdReq(req.query);
Renamed

2022-01-26 09:23 UTC, Ninjeneer commented on src/server/rest/v1/service/BillingService.ts
> +    const filteredRequest = BillingValidator.getInstance().validateBillingInvoicesGetByIdReq(req.query);
Renamed

2022-01-26 09:23 UTC, Ninjeneer commented on src/server/rest/v1/service/security/BillingSecurity.ts
> +      TenantID: sanitize(requestQuery.TenantID)
Removed

2022-01-26 09:23 UTC, Ninjeneer commented on src/server/rest/v1/validator/BillingValidator.ts
> +  private billingInvoiceGetByID: Schema = JSON.parse(fs.readFileSync(`${global.appRoot}/assets/server/rest/v1/schemas/billing/invoice-get-by-id.json`, 'utf8'));
Renamed

2022-01-26 09:23 UTC, Ninjeneer commented on src/server/rest/v1/validator/BillingValidator.ts
> +  public validateBillingInvoicesGetReq(data: Record<string, unknown>): HttpBillingInvoiceRequest {
Renamed

2022-01-26 09:23 UTC, Ninjeneer commented on src/server/rest/v1/validator/BillingValidator.ts
> +  public validateBillingInvoicesGetByIdReq(data: Record<string, unknown>): HttpBillingRequest {
Renamed

2022-01-26 09:44 UTC, ClaudeROSSI requested changes
still some naming suggestion!
Let me know what you think
Claude

2022-01-26 09:44 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    const filteredRequest = BillingValidator.getInstance().validateBillingInvoiceReq(req.query);
```suggestion
    const filteredRequest = BillingValidator.getInstance().validateBillingInvoiceGetReq(req.query);
```

2022-01-26 09:44 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    const filteredRequest = BillingValidator.getInstance().validateBillingInvoiceReq(req.query);
```suggestion
    const filteredRequest = BillingValidator.getInstance().validateBillingInvoiceGetReq(req.query);
```

2022-01-26 09:44 UTC, ClaudeROSSI commented on src/server/rest/v1/validator/BillingValidator.ts
> +  public validateBillingInvoiceReq(data: Record<string, unknown>): HttpBillingInvoiceRequest {
```suggestion
  public validateBillingInvoiceGetReq(data: Record<string, unknown>): HttpBillingInvoiceRequest {
```

2022-01-26 09:44 UTC, ClaudeROSSI commented on postman/EVSE.postman_collection.json
> +			"name": "FE-SchneiderGTCGetBorneSud",
@Ninjeneer : Is it normal that we have so many changes in that file?

2022-01-26 09:48 UTC, Ninjeneer commented on postman/EVSE.postman_collection.json
> +			"name": "FE-SchneiderGTCGetBorneSud",
Yes, I'm also updating the Postman collection along the API migration and the exported JSON is pretty big

2022-01-26 10:12 UTC, ClaudeROSSI requested changes
small comment

2022-01-26 10:12 UTC, ClaudeROSSI commented on src/server/rest/v1/service/security/BillingSecurity.ts
> +    } as HttpBillingInvoicesRequest;
Method not used!
Can you please remove old stuff which is not necessary anymore?

2022-01-26 10:32 UTC, ClaudeROSSI approved these changes
thanks

2022-01-26 11:01 UTC, LucasBrazi06 commented
> + postman collection update

You can import the OAS file in Postman in the end.

2022-01-26 12:24 UTC, Ninjeneer commented
> You can import the OAS file in Postman in the end.

Didn't know that ! Then, do we remove the JSON collection from the repo ? As anyone can generate its own collection with the OpenAPI file. This could avoid syncing both files and avoid people from using a deprecated collection

2022-01-26 13:12 UTC, LucasBrazi06 commented
> > You can import the OAS file in Postman in the end.
> 
> Didn't know that ! Then, do we remove the JSON collection from the repo ? As anyone can generate its own collection with the OpenAPI file. This could avoid syncing both files and avoid people from using a deprecated collection

No you can re-generate it once and everyone will use it right away when you will have finished the migration.

2022-01-26 13:48 UTC, LucasBrazi06 approved these changes

2022-01-26 13:49 UTC, merged