billing - check whether access control is ON
sap-labs-france/ev-server pull request #3293
Opened 2022-01-27 08:07 UTC by ClaudeROSSI

A lot of unexpected problems with that one.
This is a DRAFT - with a lot of stuff to clarify (marked with TODO comments)
@LucasBrazi06 : As discussed ... I need your advise for this PR

2022-02-11 09:51 UTC, ClaudeROSSI commented on src/server/ocpp/utils/OCPPUtils.ts
> +  public static async processTransactionBilling(tenant: Tenant, transaction: Transaction, chargingStation: ChargingStation, action: TransactionAction): Promise<void> {
@LucasBrazi06 : As discussed I have tried to align the logic with the processTransactionRoaming approach. 
But I couldn't apply exactly the same logic and I'm not satisfied with the current solution.
I do not like the fact that the signature of the **processTransactionBilling** method expects parameters that are most of the time not necessary. The charging station information is now provided but only used during the START transaction.
From my perspective, to be on the safe side, we should avoid the **switch** on the **TransactionAction**. Each event (START, STOP, END) should have its own signature to enforce the calling layer to only pass the required information.
Let me know what you think.

2022-02-11 10:32 UTC, LucasBrazi06 commented on src/server/ocpp/utils/OCPPUtils.ts
> +  public static async processTransactionBilling(tenant: Tenant, transaction: Transaction, chargingStation: ChargingStation, action: TransactionAction): Promise<void> {
We should have the same approach when processing this kind of component whatever you choose.
Make me a proposal.

2022-02-11 15:39 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +    if (!transaction.chargeBox?.siteArea?.accessControl) {
transaction.siteArea is not set when calling start transaction. 
I now pass the information as an additional parameter.

2022-02-11 15:42 UTC, ClaudeROSSI commented on src/server/ocpp/utils/OCPPUtils.ts
> +  public static async processTransactionBilling(tenant: Tenant, transaction: Transaction, chargingStation: ChargingStation, action: TransactionAction): Promise<void> {
Well ... I would be to move the split the code that we have in OCPPUtils.processTransactionBilling and move it as static methods of the BillingIntegration class.
- BillingIntegration.processStartTransation()
- BillingIntegration.processStopTransation()
- etc

But I'm not sure the same logic will match the processTransactionRoaming() use-case.

Can you review the current solution and let me know if the current implementation is acceptable?

2022-02-11 21:40 UTC, LucasBrazi06 requested changes

2022-02-11 21:40 UTC, LucasBrazi06 commented on src/assets/server/rest/v1/schemas/user/user-default-tag-car-get.json
> +      "$ref": "common#/definitions/string-ids"
It's only one charging station ID so use 'string-id'

2022-02-11 21:40 UTC, LucasBrazi06 commented on src/integration/billing/BillingIntegration.ts
> +  public checkStartTransaction(transaction: Transaction, chargingStation: ChargingStation): void {
Pass also User and SiteArea in param?

2022-02-11 21:40 UTC, LucasBrazi06 commented on src/integration/billing/BillingIntegration.ts
> +    if (!chargingStation.siteArea) {
If Org is not active, no Site Area will be provide.
Check if the org component is active.
Missing unit tests? ;-)

2022-02-11 21:40 UTC, LucasBrazi06 commented on src/server/ocpp/utils/OCPPUtils.ts
> +  public static async processTransactionBilling(tenant: Tenant, transaction: Transaction, chargingStation: ChargingStation, action: TransactionAction): Promise<void> {
I checked and pass also Site Area and User in addition to Charging Station.
I can do the same for the Roaming.

2022-02-11 21:40 UTC, LucasBrazi06 commented on src/server/rest/v1/router/api/UserRouter.ts
> -      req.query.ID = req.params.id;
Do not remove req.query.ID assignment as it has to work in the future when www and app will be fixed.

2022-02-14 08:58 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/user/user-default-tag-car-get.json
> +      "$ref": "common#/definitions/string-ids"
done

2022-02-21 17:37 UTC, ClaudeROSSI commented on src/server/ocpp/utils/OCPPUtils.ts
> +  public static async processTransactionBilling(tenant: Tenant, transaction: Transaction, chargingStation: ChargingStation, action: TransactionAction): Promise<void> {
Same comment: 4 distinct methods in **BillingFacade** class

2022-02-21 17:37 UTC, ClaudeROSSI commented on src/integration/billing/BillingIntegration.ts
> +  public checkStartTransaction(transaction: Transaction, chargingStation: ChargingStation): void {
Same comment: 4 distinct methods in **BillingFacade** class

2022-02-21 17:38 UTC, ClaudeROSSI commented on src/integration/billing/BillingIntegration.ts
> +    if (!chargingStation.siteArea) {
done.
I still have missing tests - but couldn't implement them with the new Jest framework!

2022-02-21 17:40 UTC, ClaudeROSSI commented on src/integration/billing/BillingFacade.ts
> +        if (billingImpl.checkStartTransaction(transaction, chargingStation, siteArea)) {
The **checkTransactionMethod**() is now explicitly called by the abstraction layer. The concrete implementation (i.e. STRIPE) does not need to take care of this logic anymore.

2022-02-21 17:43 UTC, ClaudeROSSI commented on src/integration/billing/BillingIntegration.ts
> +  protected async updateTransactionsBillingData(billingInvoice: BillingInvoice): Promise<void> {
This code has be moved out of the STRIPE implementation. 
It is now part of the billing abstraction to make sure all future implementations can benefit from it.

2022-02-24 21:09 UTC, LucasBrazi06 approved these changes

2022-02-24 21:09 UTC, LucasBrazi06 commented on src/server/rest/v1/service/UserService.ts
> +      const chargingStation = await ChargingStationStorage.getChargingStation(req.tenant, filteredRequest.ChargingStationID,
To use the Auth check method:
```
    const chargingStation = await UtilsService.checkAndGetChargingStationAuthorization(
      req.tenant, req.user, filteredRequest.ID, action, null, {
        withSite: true,
        withSiteArea: true,
      }, true);

```

2022-02-24 21:09 UTC, LucasBrazi06 commented on src/server/rest/v1/router/api/UserRouter.ts
> -      req.query.ID = req.params.id;
To not forget to change the WWW et App to use this URL path correctly

2022-02-24 21:31 UTC, merged