Uts for orgs
sap-labs-france/ev-server pull request #3417
Opened 2022-03-15 15:45 UTC by mahdibenromdhane

2022-03-15 15:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=3417) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=3417) before we can accept your contribution.<br/><hr/>**mahdibenromdhane** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-labs-france/ev-server?pullRequest=3417) it.</sub>

2022-03-21 10:18 UTC, ClaudeROSSI requested changes
please have a look to my comments.

BTW: automated tests are failing. Can you check why?

2022-03-21 10:18 UTC, ClaudeROSSI commented on src/storage/mongodb/SiteAreaStorage.ts
> +              companyID: DatabaseUtils.convertToObjectID(siteArea.site?.companyID)
I do not understand why we need to add companyID here.

The query is done using { withSite: true } so the information is already available, right?
>> siteArea.site?.companyID

2022-03-21 10:18 UTC, ClaudeROSSI commented on src/server/rest/v1/service/AuthorizationService.ts
> +        'createdOn', 'chargeBoxSerialNumber', 'chargePointSerialNumber', 'powerLimitUnit', 'companyID'
why don't we expose 'site.companyID' instead?

2022-03-21 10:18 UTC, ClaudeROSSI commented on src/storage/mongodb/SiteAreaStorage.ts
> +              companyID: null
idem ... this should not be necessary

2022-04-27 13:28 UTC, LucasBrazi06 commented
@ClaudeROSSI Could you check the latest Mahdi's changes?

2022-04-28 13:34 UTC, ClaudeROSSI approved these changes
@mahdibenromdhane: your code was correct.

My latest comments can be ignored. After verifying again with Serge we could confirm that the siteArea does not include the companyID and this is normal.

2022-05-04 08:12 UTC, merged