Sub-Site Area review
sap-labs-france/ev-server pull request #3456
Opened 2022-04-05 17:25 UTC by LucasBrazi06

2022-04-06 07:29 UTC, OliveGerste requested changes
@LucasBrazi06  I made some comments on the PR as I saw that it is to be reviewed.
The check tree method was moved to UtilsService. Do you think the check of the tree will never be needed anywhere else in the application? Maybe at some kind of migration task or something like this, where properties of site areas are changed?

2022-04-06 07:29 UTC, OliveGerste commented on src/server/rest/v1/service/UtilsService.ts
> +  private static buildSiteAreaTree(currentSiteArea: SiteArea, siteAreas: SiteArea[]): SiteArea {
This method is also used by the smart charging integration. So I think it should not be placed in UtilsService and should not be private.
I saw that you removed the s for multiple trees from the method name. The reason for the s was that there can be multiple trees on one site. E.G. Site: Mougins --> 3 root site areas --> 3 independent Trees which are build with this method

2022-04-06 07:29 UTC, OliveGerste commented on src/server/rest/v1/service/UtilsService.ts
> +    const siteAreas = await SiteAreaStorage.getSiteAreas(req.tenant,
req does not exist in the parameters of the method. This causes build errors.

2022-04-06 07:29 UTC, OliveGerste commented on src/server/rest/v1/service/UtilsService.ts
> +  public static async checkIfSiteAreaTreeValid(siteArea: SiteArea): Promise<void> {
The changed type definition causes errors in site area service.

2022-04-06 08:12 UTC, LucasBrazi06 commented
> @LucasBrazi06 I made some comments on the PR as I saw that it is to be reviewed. The check tree method was moved to UtilsService. Do you think the check of the tree will never be needed anywhere else in the application? Maybe at some kind of migration task or something like this, where properties of site areas are changed?

Not yet to be reviewed, that's my pipeline, otherwise I would have put it in Cross review ;-)
I haven't finished and I'm doing this exercise with Claude who will get back to you to explain/cross check.

2022-04-06 08:20 UTC, OliveGerste commented
> > @LucasBrazi06 I made some comments on the PR as I saw that it is to be reviewed. The check tree method was moved to UtilsService. Do you think the check of the tree will never be needed anywhere else in the application? Maybe at some kind of migration task or something like this, where properties of site areas are changed?
> 
> Not yet to be reviewed, that's my pipeline, otherwise I would have put it in Cross review ;-) I haven't finished and I'm doing this exercise with Claude who will get back to you to explain/cross check.

Ah okay. Now I understand. Sorry for my misunderstanding. Let me know if you need anything in this matter.

2022-04-21 16:19 UTC, LucasBrazi06 commented
Dups, new PR created from another branch

2022-04-21 16:19 UTC, closed without merging