refactor: removed useless utils checks
sap-labs-france/ev-server pull request #3511
Opened 2022-05-05 08:58 UTC by Ninjeneer

2022-05-05 09:38 UTC, LucasBrazi06 requested changes
Do you think we can also remove these methods from UtilsService?
<img width="407" alt="image" src="https://user-images.githubusercontent.com/25266945/166897941-81aaeccb-4dad-4ccc-8ceb-080659544f5b.png">

2022-05-05 10:37 UTC, Ninjeneer commented
Yes, I'm working on it.

2022-05-05 12:24 UTC, LucasBrazi06 requested changes
Some check in the remaining methods can be moved in the Json Schema:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/25266945/166922287-65f83207-29de-4f91-af92-0cdba4412b86.png">

2022-05-06 17:03 UTC, LucasBrazi06 approved these changes

2022-05-06 17:03 UTC, merged