Billing > Subaccount generation endpoint
sap-labs-france/ev-server pull request #3531
Opened 2022-05-18 07:57 UTC by Ninjeneer

2022-05-18 12:40 UTC, Ninjeneer commented
Some additional setups are required in the Stripe account used to run the tests in order to create sub-accounts (https://dashboard.stripe.com/settings/branding)

2022-05-18 15:48 UTC, ClaudeROSSI requested changes
as discussed, remove companyID and siteID from the sub account

2022-05-18 15:48 UTC, ClaudeROSSI commented on src/assets/server/rest/v1/schemas/billing/billing-create-sub-account.json
> +  ]
As discussed, please remove companyID and siteID from the sub account

2022-05-19 12:29 UTC, ClaudeROSSI approved these changes

2022-05-19 12:30 UTC, merged