Billing > Subaccounts activatation
sap-labs-france/ev-server pull request #3541
Opened 2022-05-20 09:57 UTC by Ninjeneer

2022-05-23 06:33 UTC, ClaudeROSSI requested changes
@Ninjeneer : just some i18n comments regarding the mails and notificationds.
let me know what you think.

2022-05-23 06:33 UTC, ClaudeROSSI commented on src/types/Server.ts
> +  BILLING_SUB_ACCOUNT_ACTIVATE = 'BillingSubAccountActivate',
```suggestion
  BILLING_SUB_ACCOUNT_ACTIVATE = 'BillingActivateSubAccount',
```

2022-05-23 06:33 UTC, ClaudeROSSI commented on src/assets/server/notification/email/de/billing-sub-account-activated.json
> +  "subject": "Billing - Connected account activated",
```suggestion
  "subject": "Billing account activated",
```

I would like to change the title. Is it ok with you if we simply put :
"Billing account activated" 

The user already knows that this is related to his own "connected" account

2022-05-23 06:33 UTC, ClaudeROSSI commented on src/assets/server/notification/email/de/billing-sub-account-activated.json
> +      "title": "Billing - Connected account activated",
idem

2022-05-23 06:33 UTC, ClaudeROSSI commented on src/assets/server/notification/email/fr/billing-sub-account-activated.json
> +  "subject": "Billing - Compte connecté activé",
```suggestion
  "subject": "Compte de facturation activé",
```

2022-05-23 06:33 UTC, ClaudeROSSI commented on src/assets/server/notification/email/fr/billing-sub-account-activated.json
> +      "title": "Billing - Compte connecté activé",
idem

2022-05-23 07:26 UTC, Ninjeneer commented on src/types/Server.ts
> +  BILLING_SUB_ACCOUNT_ACTIVATE = 'BillingSubAccountActivate',
I just wanted to keep the same naming convention, as we often use "EntityAction" format (TagCreate, UserImport, etc....)

2022-05-23 07:32 UTC, Ninjeneer commented on src/assets/server/notification/email/de/billing-sub-account-activated.json
> +  "subject": "Billing - Connected account activated",
Indeed, you're right. Should I also remove the "Connected" mention in the Sub-account created notification ?

2022-05-23 07:33 UTC, ClaudeROSSI commented on src/types/Server.ts
> +  BILLING_SUB_ACCOUNT_ACTIVATE = 'BillingSubAccountActivate',
> I just wanted to keep the same naming convention, as we often use "EntityAction" format (TagCreate, UserImport, etc....)

as you like ... just make sure to have the same logic for 'BillingCreateSubAccount' then.
Thanks

2022-05-24 01:39 UTC, ClaudeROSSI reviewed
@Ninjeneer : tests are not running on my side.
It sounds like the stripe account must be configured to accept sub-accounts ... 
let's have a call to discuss this

2022-05-25 08:12 UTC, ClaudeROSSI approved these changes

2022-05-25 08:12 UTC, merged