Billing > send onboarding endpoint
sap-labs-france/ev-server pull request #3590
Opened 2022-06-06 13:10 UTC by Ninjeneer

2022-06-06 17:19 UTC, ClaudeROSSI requested changes
some minor comments ... mainly naming issues!
thanks

2022-06-06 17:19 UTC, ClaudeROSSI commented on src/types/Server.ts
> +  BILLING_SUB_ACCOUNT_SEND_ONBOARDING = 'BillingSubAccountSendOnboarding',
I would like to rename it!

```suggestion
  BILLING_SUB_ACCOUNT_ONBOARD = 'BillingSubAccountOnboard',
```

2022-06-06 17:19 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    if (subAccount.status === BillingAccountStatus.IDLE) {
Activation should only be allowed when in a PENDING state. right?

```suggestion
    if (subAccount.status !== BillingAccountStatus.PENDING) {
```

2022-06-06 17:19 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +        message: 'Sub account onboarding has not been sent',
```suggestion
        message: 'Sub-account onboarding aborted - current status should be PENDING',
```

2022-06-06 17:19 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +  public static async handleSendSubAccountOnboarding(action: ServerAction, req: Request, res: Response, next: NextFunction): Promise<void> {
i would like to rename it:

>> handleOnboardSubaccount

ok?

2022-06-06 17:19 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    if (subAccount.status === BillingAccountStatus.PENDING) {
Onboarding should be alloewd when status is IDLE. ok?

```suggestion
    if (subAccount.status !== BillingAccountStatus.IDLE) {
```

2022-06-06 17:19 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +        message: 'Sub account onboarding is already sent',
```suggestion
        message: 'Sub-account onboarding aborted - current status should be IDLE',
```

2022-06-06 17:19 UTC, ClaudeROSSI commented on src/types/Authorization.ts
> +  BILLING_SEND_SUB_ACCOUNT_ONBOARDING = 'BillingSendSubAccountOnboarding',
rename it as well!

2022-06-07 07:46 UTC, Ninjeneer commented on src/server/rest/v1/service/BillingService.ts
> +    if (subAccount.status === BillingAccountStatus.IDLE) {
I splitted in two different `if` to specify the error message. But we can also check with `!==` and return a single error message. What do you think ?

2022-06-07 07:53 UTC, ClaudeROSSI commented on src/server/rest/v1/service/BillingService.ts
> +    if (subAccount.status === BillingAccountStatus.IDLE) {
as you like ... just make sure that we are generic enough in case we add (later on) additional STATUS (such as ERROR)

2022-06-07 12:45 UTC, ClaudeROSSI approved these changes
ok

2022-06-07 13:28 UTC, merged