New user context method based on handle get user default tag car
sap-labs-france/ev-server pull request #3975
Opened 2022-11-09 15:18 UTC by OliveGerste

2022-11-15 07:17 UTC, ClaudeROSSI requested changes
I'll update our wiki page to make sure we are on the same page regarding the main use-case that Hanno has in mind.
We will then do a sync again.

2022-11-15 07:17 UTC, ClaudeROSSI commented on src/server/rest/v1/service/UserService.ts
> +    let prioritizationParameters: PrioritizationParameters;
**PrioritizationParameters** is a specific type from the SmartCharging settings. I don't like the fact that we directly pass this information to the client.

The contract between the client and the server should use a dedicated interface in order to abstract a bit from the actual implementation.
e.g.: **SmartChargingSessionParameters** 

I discussed the main use-case again (with our boss) and this interface will certainly combine information coming from both the **SmartCharging** settings but also from the Site or Site Area (or maybe one day from the user preferences).

2022-11-15 07:17 UTC, ClaudeROSSI commented on src/types/Setting.ts
> +  defaultTargetStateOfCharge: number;
As already mentioned, this interface is for the global settings.
We need a second interface to define the contract with the client (i.e.: the mobile app and the web app).
I'll update our wiki page to make sure we are on the same page regarding the actual use-case.

2022-11-15 16:16 UTC, ClaudeROSSI commented on src/types/Setting.ts
> +  defaultTargetStateOfCharge: number;
@OliveGerste, @AlixH : PLease have a look to my proposal at:
- https://wiki.one.int.sap/wiki/display/OpenEMob/Smart+Charging+-+Departure+Time
Let me know if you feel confortable with it!

2022-11-15 17:48 UTC, OliveGerste commented on src/types/Setting.ts
> +  defaultTargetStateOfCharge: number;
Looks good to me 👍

2022-11-16 10:09 UTC, AlixH commented on src/types/Setting.ts
> +  defaultTargetStateOfCharge: number;
I think carStateOfCharge should also be null when on a DC connector so the UI can hide it
Everything is clear otherwise

2022-11-23 17:01 UTC, merged