Monitoring
sap-labs-france/ev-server pull request #3981
Opened 2022-11-16 15:47 UTC by lmargaron

2022-11-16 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=3981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=3981) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-labs-france/ev-server?pullRequest=3981) it.</sub>

2022-11-17 20:26 UTC, LucasBrazi06 commented
@lmargaron Salut poulet, comment ca va !?
Cool que tu bosses sur ce topic :-) !!!

Pour info, dans la classe Logging tu as les méthodes traceXXX() qui te donnent des infos sur les perfs, le volume de données + infos (tenant, url, action...), infos qui peuvent servir de filtre dans Grafana ;-).

![image](https://user-images.githubusercontent.com/25266945/202552439-28a85c98-217f-4e79-9790-88460dd4ff54.png)

Amuse-toi bien !!!

2022-11-17 22:46 UTC, ClaudeROSSI requested changes
check my comments.
Let's discuss tomorrow!

2022-11-17 22:46 UTC, ClaudeROSSI commented on src/storage/mongodb/MongoDBStorage.ts
> +    const connections = new Set<any>();
@lmargaron : Do we need a Set<> here ... why don't we just maintain a counter?

2022-11-17 22:46 UTC, ClaudeROSSI commented on src/monitoring/prometheus/PrometheusMonitoringServer.ts
> +    global.monitoringServer = this;
@lmargaron : I do not understand this global stuff.
If the monitoring server is really a server, it may run in its own nodejs process. So, referencing it in this 'global' object won.t make it available to the other server's (like ocpp-j).

Let's have a sync on this tommorrow!

2022-11-21 15:14 UTC, lmargaron commented
> @lmargaron Salut poulet, comment ca va !? Cool que tu bosses sur ce topic :-) !!!
> 
> Pour info, dans la classe Logging tu as les méthodes traceXXX() qui te donnent des infos sur les perfs, le volume de données + infos (tenant, url, action...), infos qui peuvent servir de filtre dans Grafana ;-).
> 
> ![image](https://user-images.githubusercontent.com/25266945/202552439-28a85c98-217f-4e79-9790-88460dd4ff54.png)
> 
> Amuse-toi bien !!!

Hello Serge,
ca roule ?

Est ce que il faut exporter tous les performances record dans prometheus ou seulement pour la db ?

export default interface PerformanceRecord {
  id?: string;
  tenantSubdomain: string;
  timestamp: Date;
  host: string;
  action: ServerAction|string;
  group: PerformanceRecordGroup;
  server?: string;
  durationMs?: number;
  reqSizeKb?: number;
  resSizeKb?: number;
  httpUrl?: string;
  httpMethod?: string;
  egress?: boolean;
  httpResponseCode?: number;
  chargingStationID?: string;
  userID?: string;
}

Concernant les connections db j ai exporte 3 metrics pour les connections db 

    const connections = new Set<any>();
    mongoDBClient.on('connectionCreated',
      (event) => global.monitoringServer.getGauge(Constants.MONGODB_CONNECTION_CREATED).inc(1)
    );
    mongoDBClient.on('connectionClosed',
      (event) => global.monitoringServer.getGauge(Constants.MONGODB_CONNECTION_CLOSED).inc(1)
    );
    mongoDBClient.on('connectionReady',
      (event) => {
        connections.add(event.connectionId);
        global.monitoringServer.getGauge(Constants.MONGODB_CONNECTION_READY).set(connections.size);
      }
    );


Pour les websockets j ai exporte les metrics que tu vais code dans JSONOCPPServer.monitorWSConnections()

        global.monitoringServer.getGauge(Constants.WEB_SOCKET_RUNNING_REQUEST_RESPONSE).set(this.runningWSMessages);        global.monitoringServer.getGauge(Constants.WEB_SOCKET_OCPP_CONNECTIONS_COUNT).set(this.jsonWSConnections.size);      global.monitoringServer.getGauge(Constants.WEB_SOCKET_REST_CONNECTIONS_COUNT).set(this.jsonRestWSConnections.size)
global.monitoringServer.getGauge(Constants.WEB_SOCKET_CURRRENT_REQUEST).set(numberOfCurrentRequests);
        global.monitoringServer.getGauge(Constants.WEB_SOCKET_RUNNING_REQUEST).set(Object.keys(this.runningWSRequestsMessages).length);
        global.monitoringServer.getGauge(Constants.WEB_SOCKET_QUEUED_REQUEST).set(this.waitingWSMessages);
        if (this.isDebug()) {
          Logging.logConsoleDebug('=====================================');
          Logging.logConsoleDebug(`** ${this.jsonWSConnections.size} JSON Connection(s)`);
          Logging.logConsoleDebug(`** ${numberOfCurrentRequests} JSON WS Requests in cache with a size of ${sizeOfCurrentRequestsBytes / 1000} kB`);
          Logging.logConsoleDebug(`** ${this.jsonRestWSConnections.size} REST Connection(s)`);
          Logging.logConsoleDebug(`** ${Object.keys(this.runningWSRequestsMessages).length} running WS Requests`);
          Logging.logConsoleDebug(`** ${this.runningWSMessages} running WS Messages (Requests + Responses)`);
          Logging.logConsoleDebug(`** ${this.waitingWSMessages} queued WS Message(s)`);
          Logging.logConsoleDebug('=====================================');
        }

2022-11-21 19:22 UTC, ClaudeROSSI approved these changes
ok. Let's try this first version on QA

2022-11-21 19:23 UTC, merged

2022-11-23 10:00 UTC, LucasBrazi06 commented
> > @lmargaron Salut poulet, comment ca va !? Cool que tu bosses sur ce topic :-) !!!
> > Pour info, dans la classe Logging tu as les méthodes traceXXX() qui te donnent des infos sur les perfs, le volume de données + infos (tenant, url, action...), infos qui peuvent servir de filtre dans Grafana ;-).
> > ![image](https://user-images.githubusercontent.com/25266945/202552439-28a85c98-217f-4e79-9790-88460dd4ff54.png)
> > Amuse-toi bien !!!
> 
> Hello Serge, ca roule ?
> 
> Est ce que il faut exporter tous les performances record dans prometheus ou seulement pour la db ?
> 
> export default interface PerformanceRecord { id?: string; tenantSubdomain: string; timestamp: Date; host: string; action: ServerAction|string; group: PerformanceRecordGroup; server?: string; durationMs?: number; reqSizeKb?: number; resSizeKb?: number; httpUrl?: string; httpMethod?: string; egress?: boolean; httpResponseCode?: number; chargingStationID?: string; userID?: string; }
> 

Tous les kpis doivent etre remonté dans Prometheus pour que tu puisses les filtrer dans Grafana.

> Concernant les connections db j ai exporte 3 metrics pour les connections db
> 
> ```
> const connections = new Set<any>();
> mongoDBClient.on('connectionCreated',
>   (event) => global.monitoringServer.getGauge(Constants.MONGODB_CONNECTION_CREATED).inc(1)
> );
> mongoDBClient.on('connectionClosed',
>   (event) => global.monitoringServer.getGauge(Constants.MONGODB_CONNECTION_CLOSED).inc(1)
> );
> mongoDBClient.on('connectionReady',
>   (event) => {
>     connections.add(event.connectionId);
>     global.monitoringServer.getGauge(Constants.MONGODB_CONNECTION_READY).set(connections.size);
>   }
> );
> ```

Oui c'est bien!

> 
> Pour les websockets j ai exporte les metrics que tu vais code dans JSONOCPPServer.monitorWSConnections()
> 
> ```
> global.monitoringServer.getGauge(Constants.WEB_SOCKET_RUNNING_REQUEST_RESPONSE).set(this.runningWSMessages);        global.monitoringServer.getGauge(Constants.WEB_SOCKET_OCPP_CONNECTIONS_COUNT).set(this.jsonWSConnections.size);      global.monitoringServer.getGauge(Constants.WEB_SOCKET_REST_CONNECTIONS_COUNT).set(this.jsonRestWSConnections.size)
> global.monitoringServer.getGauge(Constants.WEB_SOCKET_CURRRENT_REQUEST).set(numberOfCurrentRequests);
> global.monitoringServer.getGauge(Constants.WEB_SOCKET_RUNNING_REQUEST).set(Object.keys(this.runningWSRequestsMessages).length);
> global.monitoringServer.getGauge(Constants.WEB_SOCKET_QUEUED_REQUEST).set(this.waitingWSMessages);
>         if (this.isDebug()) {
>           Logging.logConsoleDebug('=====================================');
>           Logging.logConsoleDebug(`** ${this.jsonWSConnections.size} JSON Connection(s)`);
>           Logging.logConsoleDebug(`** ${numberOfCurrentRequests} JSON WS Requests in cache with a size of ${sizeOfCurrentRequestsBytes / 1000} kB`);
>           Logging.logConsoleDebug(`** ${this.jsonRestWSConnections.size} REST Connection(s)`);
>           Logging.logConsoleDebug(`** ${Object.keys(this.runningWSRequestsMessages).length} running WS Requests`);
>           Logging.logConsoleDebug(`** ${this.runningWSMessages} running WS Messages (Requests + Responses)`);
>           Logging.logConsoleDebug(`** ${this.waitingWSMessages} queued WS Message(s)`);
>           Logging.logConsoleDebug('=====================================');
>         }
> ```

Oui c'est bien aussi!
Bise.