move handleForceSynchronizeUser to restful
sap-labs-france/ev-server pull request #4165
Opened 2023-03-30 17:11 UTC by mahdibenromdhane

2023-03-30 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=4165) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-labs-france/ev-server?pullRequest=4165) before we can accept your contribution.<br/><hr/>**mahdibenromdhane** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-labs-france/ev-server?pullRequest=4165) it.</sub>

2023-03-31 06:48 UTC, ClaudeROSSI commented on src/server/rest/v1/router/api/BillingRouter.ts
> +
@mahdibenromdhane : I would like to have an endpoint similar to

>> RESTServerRoute.REST_BILLING_TRANSFER_FINALIZE

2023-03-31 06:50 UTC, ClaudeROSSI requested changes
please check my comments

2023-03-31 06:50 UTC, ClaudeROSSI commented on src/types/Server.ts
> +  REST_FORCE_SYNCHRONIZE_USER = 'billing/force-synchronize-user',
PLease chenge it to:

REST_BILLING_USER_SYNCHRONIZE = 'billing/users/:id/synchronize',

I need the id in the URL

The HTTP verb should be PATCH instead of POST

Let me know what you think!

2023-03-31 16:33 UTC, mahdibenromdhane commented on src/types/Server.ts
> +  REST_FORCE_SYNCHRONIZE_USER = 'billing/force-synchronize-user',
Yes, it make more sense this way. 
Done for the changes.

2023-03-31 16:34 UTC, mahdibenromdhane commented on src/server/rest/v1/router/api/BillingRouter.ts
> +      req.body.id = req.params.id;
@ClaudeROSSI let me know if you want to use the directly the req.params in the filteredrequest.
Meanwhile it works this way.

2023-04-03 19:30 UTC, ClaudeROSSI approved these changes
thanks

2023-04-03 19:31 UTC, merged